# Generated by Django 5.1.3 on 2024-11-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_completed_task_description_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
